// this file generated by ResourceGenerators.RegenerateProxyClasses

using System;

namespace CommandDotNet.Spectre
{
    // this class generated by ResourcesDef.GenerateProxyClass
    public class ResourcesProxy : Resources
    {
        private readonly Func<string, string?> _localize;

        public ResourcesProxy(Func<string, string?> localize)
        {
            _localize = localize ?? throw new ArgumentNullException(nameof(localize));
        }

        public override string Selection_paging_instructions(string? typeDisplayName) =>
            _localize(base.Selection_paging_instructions("{0}"))
            ?? base.Selection_paging_instructions(typeDisplayName);

    }
}