// this file generated by ResourceGenerators.RegenerateProxyClasses

using System;

namespace CommandDotNet.Spectre
{
    // this class generated by ResourcesDef.GenerateProxyClass
    public class ResourcesProxy : Resources
    {
        private readonly Func<string?, string?> _localize;

        public ResourcesProxy(Func<string, string?> localize)
        {
            if (localize is null)
            {
                throw new ArgumentNullException(nameof(localize));
            }

            _localize = s => s is null ? null : localize(s);
        }

        public override string? Selection_paging_instructions(string argumentName) =>
            _localize(base.Selection_paging_instructions("{0}"))
            ?? base.Selection_paging_instructions(argumentName);

        public override string? MultiSelection_selection_instructions(string argumentName) =>
        _localize(base.MultiSelection_selection_instructions("{0}"))
            ?? base.Selection_paging_instructions(argumentName);
        
    }
}