language: csharp
mono: none

git:
  depth: false

services:
  - docker

stages:
    - name: test
    - name: deploy
      if: tag IS present

#--------- TEST JOBS --------------
jobs:
    include:
        - stage: test
          env:
            - secure: IAG2C9zBIJ19x0Ezqshy5En1d0VWut7x7OnlJevMN90Y77NPu3gCT8bMC1r34KM5xLqqPcAUVl3dWWp3d3yJGPbtgJ33Jglu0UAc36I9PDhZ6gQY5cOu/TTKdW42BLMzj2ExGKWJkm3JO/NYe3rob2GwNK/dgvz3Z1acEs0BNR+yYT6wVLhPmpDXbV/UjqovWImc6IH/avZVfxmtnNuvtqOfLIAidSR4B3GyRRYqvHNewC8m3YdTgRhAQSZrzB+KVGJ6arMX6D6pVZqDknvPcqqYFd1qNTfgAKwbUg+/BCoUsSF4H1KsyoNU8yOyWTF5z6l6WfNtZDS+5eXS3/2BJlLQzA4Fn1o7EqgOY1a4gP67YNt3gddr8Fb+Vqdxt6LdMi+ZHbG/oIZPurZenuXGKtR4WfofH58MnM5yY7A/Pw/IoRrvW7yCxHA9j1Zciv8bhodHoz7kdt35JJKhkKfMLjkhPV18toW/kwOjxzgHmcYnx45KLG3p3EmWOzSVCZpR4J4l0s9Iuq48tUynf15L+ox/zEdDtgnfld974UhI07XwXhMwBfbD8rs+QtAljwnt2ceIiuObuwqnMIzRLposnJMiR0ZCNOhyTdmCsMe909e1KwgtmGEAIA1bHQz9iSHMlnFGG9b6k7Q1KILY4RfOdCWtgSmaUP207TW5/F1dS1c=
          after_success:
            - ./discord-send.sh success $WEBHOOK_URL
          after_failure:
            - ./discord-send.sh failure $WEBHOOK_URL
          name: test on osx
          os: osx
          dotnet: 3.1.102
          script: dotnet test CommandDotNet.Tests/CommandDotNet.Tests.csproj
        - name: test on linux
          os: linux
          dotnet: 3.1.102
          script: dotnet test CommandDotNet.Tests/CommandDotNet.Tests.csproj
        - name: test on windows
          os: windows
          script: dotnet test CommandDotNet.Tests/CommandDotNet.Tests.csproj
        #-----------------------------------

        #--------- DEPLOYMENT JOB ----------  
        - stage: deploy
          name: nuget & github release
          script: ./deploy.sh
          os: linux
          dotnet: 3.1.102
          after_success:
            - ./discord-send.sh success $WEBHOOK_URL
          after_failure:
            - ./discord-send.sh failure $WEBHOOK_URL
          env:
              - secure: rzK8y4HE7yCVPStFdVttd1ApJ15xGhiGObJsHifi5ulaR/4POUU5o+6Bf/kLxCbhPeK0VBT5Zlt2WUNYq19IF8PbwZqADMQwc8NJVYX78UEbtbq5NaI2xFTbLC5Ng8GWcl5cEhl68pTMHIbqkAmUW7H3ESQVqz7DBG2oehCWXlEggI6hiXgS/QWE/W6YdLMoitPZTATeM1FXs3ZT1IMRGCpcl4mVkK8bEr8fFemujWOD7ymZYZUAr97B9u6oPz/mgW0BsWKNQfHkS6t92N/1WZyX8voJ4hszKvJedYaw3u8FVJvG4KNhMtT24GQl2b8MCkqVo6U41kRHSfkg5uNIigSy/mYKyT8WQWf/bT/WrKyVSepKcHaT1rYdKac/hmOTa66804P44ZTa9l0J2r9fTEg7qPRmC83e81KprIg6WptE9UpN9bRjtzULa7gZyAtoO8TgUCEt1+siP/cGqUtU/gwG4Pv/Bgxy6CIda5NLzNDCTZqWdkJkdogKLFDzjawDn1LG8j8SlGo7h6wb92YcS+EQLww4fk6CSJU7IY35tfzxGG3onWvR9sUn4bjulROOIVAEmpwzLmuSsvQZ5Jv8dnp6m0KPJGHFJWzYPUsmVDFPRZul6y1MROIax36AtQnUCu3LMQu5dAwizOvmmE6DPopfJjn1gHiFHU/nSL7Qcgg=
              - secure: IAG2C9zBIJ19x0Ezqshy5En1d0VWut7x7OnlJevMN90Y77NPu3gCT8bMC1r34KM5xLqqPcAUVl3dWWp3d3yJGPbtgJ33Jglu0UAc36I9PDhZ6gQY5cOu/TTKdW42BLMzj2ExGKWJkm3JO/NYe3rob2GwNK/dgvz3Z1acEs0BNR+yYT6wVLhPmpDXbV/UjqovWImc6IH/avZVfxmtnNuvtqOfLIAidSR4B3GyRRYqvHNewC8m3YdTgRhAQSZrzB+KVGJ6arMX6D6pVZqDknvPcqqYFd1qNTfgAKwbUg+/BCoUsSF4H1KsyoNU8yOyWTF5z6l6WfNtZDS+5eXS3/2BJlLQzA4Fn1o7EqgOY1a4gP67YNt3gddr8Fb+Vqdxt6LdMi+ZHbG/oIZPurZenuXGKtR4WfofH58MnM5yY7A/Pw/IoRrvW7yCxHA9j1Zciv8bhodHoz7kdt35JJKhkKfMLjkhPV18toW/kwOjxzgHmcYnx45KLG3p3EmWOzSVCZpR4J4l0s9Iuq48tUynf15L+ox/zEdDtgnfld974UhI07XwXhMwBfbD8rs+QtAljwnt2ceIiuObuwqnMIzRLposnJMiR0ZCNOhyTdmCsMe909e1KwgtmGEAIA1bHQz9iSHMlnFGG9b6k7Q1KILY4RfOdCWtgSmaUP207TW5/F1dS1c=
        #-----------------------------------
#-----------------------------------

# cache:
#   directories:
#     - $HOME/.nuget/packages  