version: 2.7.{build}-beta
branches:
  except:
  - gh-pages
skip_tags: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: build.bat
test_script:
- cmd: dotnet test CommandDotNet.Tests/CommandDotNet.Tests.csproj
artifacts:
- path: CommandDotNet/output/**
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: IP4hm35AxgCDx81eH83zzHRg3fUFRAgQYK8mKOwOfSPLDc6qkXdEWfFq6GeXI9s5
  skip_symbols: false
  artifact: Nuget
  on:
    branch: release
- provider: GitHub
  auth_token:
    secure: CYhAEm/f6dhXf8d5F46G8YTfgHnU7UFVCJUknwIbNZzK06XHNHSIaPmZ+VeV4Afx
  on:
    branch: release
notifications:
- provider: Email
  to:
  - bilal.m.fazlani@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true