site_name: CommandDotNet
site_description: Model your command line application interface in a class
repo_name: 'bilal-fazlani/commanddotnet'
repo_url: 'https://github.com/bilal-fazlani/commanddotnet'
site_url: https://bilal-fazlani.github.io/commanddotnet

nav:
  - Current Version:
    - Introduction: index.md
    - Quick Start: quick-start.md
    - Defining Commands:
      - Parameters: parameters.md
      - Attributes: attributes.md
      - Constructors: constructors.md
      - Default method: default-method.md
      - Default values: default-values.md
      - Collections: collections.md
      - Argument Models: argument-models.md
      - Async methods: async-methods.md
      - Custom return codes: custom-return-codes.md
      - Nesting commands: nesting-commands.md
      - Exceptions: exceptions.md
    - Extras:
      - directives.md
      - Fluent validation for parameters: fluent-validation-for-argument-models.md
      - Settings: settings.md
    - Extensibility:
      - Dependency Injection: dependency-injection.md
      - Parameter types: parameter-types.md
      - Custom interceptors: custom-interceptors.md
  - Version 3 (Preview):
    - Introduction: V3/index.md
    - V3/v3-changes.md
    - Defining Commands:
      - V3/DefiningCommands/argument-terminology.md
      - V3/DefiningCommands/argument-arity.md
      - V3/DefiningCommands/argument-models.md
      - V3/DefiningCommands/option-or-operand.md
      - V3/DefiningCommands/passwords.md
      - V3/DefiningCommands/piped-arguments.md
      - V3/DefiningCommands/prompting.md
    - Extensibility:
      - V3/Extensibility/middleware.md
      - V3/Extensibility/interceptors.md
      - V3/Extensibility/parameter-resolvers.md
    - Extras:
      - V3/Extras/test-tools.md
      - V3/Extras/cancellation.md
      - V3/Extras/response-files.md
      - V3/Extras/newer-release-alerts.md
theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'indigo'
    accent: 'pink'  
  logo: 'img/small-logo.svg'

google_analytics:
  - 'UA-39358317-3'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
     permalink: "#"   

plugins:
  - search
  #- git-revision-date-localized     

# Customization
extra:
  disqus: 'command-dot-net'
  social:
    - type: 'github'
      link: 'https://github.com/bilal-fazlani'
    - type: 'twitter'
      link: 'https://twitter.com/bilal_fazlani'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/bilal-fazlani/'