site_name: CommandDotNet
site_description: Model your command line application interface in a class
repo_name: 'bilal-fazlani/commanddotnet'
repo_url: 'https://github.com/bilal-fazlani/commanddotnet'

strict: true

nav:
    - Documentation:
      - Introduction: index.md
      - getting-started.md
      - Defining Commands:
        - DefiningCommands/argument-terminology.md
        - DefiningCommands/commands.md
        - DefiningCommands/subcommands.md
        - DefiningCommands/arguments.md
        - DefiningCommands/argument-collections.md
        - DefiningCommands/argument-types.md
        - DefiningCommands/argument-models.md
        - DefiningCommands/argument-arity.md
        - DefiningCommands/option-or-operand.md
        - DefiningCommands/passwords.md
        - DefiningCommands/separated-arguments.md
      - Extensibility:
        - Extensibility/help.md
        - Extensibility/directives.md
        - Extensibility/parameter-types.md
        - Extensibility/parameter-resolvers.md
        - Extensibility/middleware.md
        - Extensibility/interceptors.md 
        - Extensibility/token-transformations.md
      - Middleware:
        - Middleware/default-middleware.md
        - Middleware/app-version.md
        - Middleware/cancellation.md
        - Middleware/default-values-from-config.md
        - Middleware/dependency-injection.md
        - Middleware/fluent-validation-for-argument-models.md
        - Middleware/name-casing.md
        - Middleware/piped-arguments.md
        - Middleware/prompting.md
        - Middleware/response-files.md
        - Middleware/typo-suggestions.md
        - Middleware/newer-release-alerts.md
      - Diagnostics:
        - Diagnostics/debug-directive.md
        - Diagnostics/parse-directive.md
        - Diagnostics/command-logger.md
        - Diagnostics/exceptions.md
      - test-tools.md
    - Release Notes:
      - ReleaseNotes/whats-new-in-v3.md
      - ReleaseNotes/CommandDotNet.md
      - ReleaseNotes/CommandDotNet.FluentValidation.md
      - ReleaseNotes/CommandDotNet.IoC.Autofac.md
      - ReleaseNotes/CommandDotNet.IoC.MicrosoftDependencyInjection.md
      - ReleaseNotes/CommandDotNet.IoC.SimpleInjector.md
      - ReleaseNotes/CommandDotNet.NameCasing.md
      - ReleaseNotes/CommandDotNet.TestTools.md
    - Roadmap: 
      - ReleaseNotes/roadmap.md
theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'black'
    accent: 'red'  
  logo: 'img/small-logo.svg'

google_analytics:
  - 'UA-39358317-3'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
     permalink: "#"   

plugins:
  - search
  # - git-revision-date-localized
  - autolinks

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bilal-fazlani'
    - type: 'twitter'
      link: 'https://twitter.com/bilal_fazlani'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/bilal-fazlani/'
