// this file generated by ResourceGenerators.RegenerateProxyClasses

using System;

namespace CommandDotNet.FluentValidation
{
    // this class generated by ResourcesDef.GenerateProxyClass
    public class ResourcesProxy : Resources
    {
        private readonly Func<string, string?> _localize;

        public ResourcesProxy(Func<string, string?> localize)
        {
            _localize = localize ?? throw new ArgumentNullException(nameof(localize));
        }

        public override string Error_Argument_model_is_invalid(string modelName) =>
            _localize(base.Error_Argument_model_is_invalid("{0}"))
            ?? base.Error_Argument_model_is_invalid(modelName);
        public override string Error_Could_not_create_instance_of(string name) =>
            _localize(base.Error_Could_not_create_instance_of("{0}"))
            ?? base.Error_Could_not_create_instance_of(name);

    }
}