// this file generated by ResourceGenerators.RegenerateProxyClasses

using System;
using JetBrains.Annotations;

namespace CommandDotNet.DataAnnotations
{
    // this class generated by ResourcesDef.GenerateProxyClass
    [PublicAPI]
    public class ResourcesProxy(Func<string, string?> localize, bool memberNameAsKey = false) : Resources
    {
        private readonly Func<string, string?> _localize = localize ?? throw new ArgumentNullException(nameof(localize));

        private static string? Format(string? value, params object?[] args) =>
            value is null ? null : string.Format(value, args);

        public override string Error_DataAnnotation_phrases_to_replace_with_argument_name() =>
            _localize(memberNameAsKey 
                ? "Error_DataAnnotation_phrases_to_replace_with_argument_name"
                : base.Error_DataAnnotation_phrases_to_replace_with_argument_name())
            ?? base.Error_DataAnnotation_phrases_to_replace_with_argument_name();

    }
}